# version: 1.0.0

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$python\
$character"""

[fill]
symbol = ' '

[time]
disabled = false
format = "[$time]($style)"
time_format = "%T"
utc_time_offset = "local"
style = "#494d64"
