# https://starship.rs/config/

format = """
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$line_break\
$shell\
$character"""

[character]
success_symbol = '[\$](bold green)'
error_symbol = '[\$](bold red)'

[directory]
truncation_length = 8
truncation_symbol = '…/'

