#!/bin/bash

today=$(date +"%Y-%m-%d")
file="$HOME/Documents/LukasNotes/periodic-notes/daily-notes/$today.md"

cd "$HOME/Documents/LukasNotes" || exit

new_note() {
	touch "$file"

	# Format the file with the daily template
	cat <<EOF >"$file"
# $today

## Tasks

- [ ] Notizen von gestern prüfen

## Notes

- ...
EOF

}

# If the daily note does not exist, create a new one.
# this uses the test command with the -f flag.
if [ ! -f "$file" ]; then
	echo "File does not exist, creating new daily note."
	new_note
fi

# Open the daily note at the bottom of the file in insert mode
nvim '+ normal Gzzo' "$file"
