# https://alacritty.org/config-alacritty.html

import = [
  #"~/.dotfiles/.config/alacritty/themes/catppuccin/catppuccin-mocha.toml"
  #"~/.dotfiles/.config/alacritty/themes/poimandres/theme/poimandres-storm.toml"
  "~/.dotfiles/.config/alacritty/themes/poimandres/theme/poimandres.toml"
]

working_directory = "/Users/macpc05/Repositories"

[env]
TERM = "xterm-256color"

[window]
padding.x = 8
padding.y = 4
decorations = "buttonless"

[font]
size = 14.0
normal = { family = "Hack Nerd Font" }

[cursor]
style = { shape = "Beam", blinking = "On" }
